name: Production CD

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.DEPLOYMENT_HOST }}
      USER: ${{ secrets.DEPLOYMENT_USER }}
      CONFIG_PATH: ${{ secrets.CONFIG_PATH }}

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - uses: actions/setup-elixir@v1
      with:
        otp-version: 23.0
        elixir-version: 1.10.4

    - uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Initializing Hex
      run: mix local.hex --force

    - name: Initializing rebar
      run: mix local.rebar --force

    - name: Install dependencies
      run: mix do deps.get, compile
    
    - name: Copy config file
      uses: appleboy/scp-action@master
      with:
        host: $HOST
        username: $USER
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: $USER@HOST:$CONFIG_PATH
        target: $GITHUB_WORKSPACE/.deliver/config

    - name: Build release to production
      run: mix edeliver build release to production --mix-env=prod --branch=production --verbose

    - name: Deploy build to production
      run: mix edeliver deploy release to production mix-env=prod --verbose
      
    - name: Restart production server
      run: mix edeliver restart production --mix-env=prod --verbose

    - name: Run migrations
      run: mix edeliver migrate production --mix-env=prod --verbose
